name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
                pyinstaller -F -n webex-backup-mac webex-backup.py &&
                cd dist/ &&
                zip webex-backup-mac webex-backup-mac.zip/
            OUT_FILE_NAME: webex-backup-mac.zip
            ASSET_MIME: application/zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller -F -n webex-backup-windows webex-backup.py
            OUT_FILE_NAME: webex-backup-windows.exe
            ASSET_MIME: application/vnd.microsoft.portable-executable
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}
