name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application for linux
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .
